"use client";
import { useEffect,useState } from "react";
import Link from "next/link";

type Job={id:string;title:string;company:string;location?:string|null};
type Application={id:string;status:string;job?:Job|null};
type Signal={id:string;category:string;confidence:number;suggestedStatus:string|null;reason:string;subject?:string;sender?:string;receivedAt?:string;applied:boolean;applicationId?:string|null;recruiterName?:string|null;recruiterEmail?:string|null;matchedScore?:number|null;matchMethod?:string|null;ambiguous?:boolean;job?:Job|null;application?:Application|null};
type Timeline={applicationId:string;job:Job;status:string;createdAt:string;updatedAt:string;appliedAt?:string|null;events:{id:string;category:string;status:string|null;subject:string|null;reason:string;recruiterName?:string|null;recruiterEmail?:string|null;receivedAt:string;confidence:number;applied:boolean}[]};
type GmailStatus={connected:boolean;connection?:{email?:string;connectedAt?:string}|null};
type Draft={subject:string;body:string};
const method=(m?:string|null)=>m==="ai"?"AI match":m==="deterministic"?"Deterministic":m==="manual"?"Manual":m==="ai-ambiguous"?"Needs review":m==="ai-unmatched"?"Unmatched":"Analyzed";
const confidence=(v?:number|null)=>typeof v==="number"?`${Math.round(v*100)}%`:"—";
const eventLabel=(c:string)=>c.replaceAll("_"," ");
export default function IntelligencePage(){
 const[status,setStatus]=useState<GmailStatus|null>(null),[signals,setSignals]=useState<Signal[]>([]),[applications,setApplications]=useState<Application[]>([]),[timeline,setTimeline]=useState<Timeline[]>([]),[scanning,setScanning]=useState(false),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState(""),[subject,setSubject]=useState(""),[body,setBody]=useState(""),[preview,setPreview]=useState<any>(null),[loading,setLoading]=useState(false),[draft,setDraft]=useState<Draft|null>(null),[draftBusy,setDraftBusy]=useState<string|null>(null);
 async function load(){try{const[s,a,g,t]=await Promise.all([fetch("/api/gmail/signals"),fetch("/api/applications"),fetch("/api/gmail/status"),fetch("/api/intelligence/timeline")]);if(s.status===401){location.href="/login";return}const sd=await s.json(),ad=await a.json(),gd=await g.json(),td=await t.json();setSignals(sd.signals||[]);setApplications(ad.applications||[]);setStatus(gd);setTimeline(td.timeline||[])}catch{setError("Could not load Gmail intelligence.")}}
 useEffect(()=>{load();const q=new URLSearchParams(location.search);if(q.get("gmail")==="error")setError("Google connection failed. Check your OAuth configuration and try again.");if(q.get("gmail")==="reauthorize")setError("Google did not return a refresh token. Reconnect and approve Gmail access.")},[]);
 async function scan(){setScanning(true);setError("");try{const r=await fetch("/api/gmail/scan",{method:"POST"}),d=await r.json();if(!r.ok)throw new Error(d.error||"Scan failed.");await load()}catch(e){setError(e instanceof Error?e.message:"Gmail scan failed.")}finally{setScanning(false)}}
 async function match(signalId:string,applicationId:string){setBusy(signalId);setError("");try{const r=await fetch("/api/gmail/signals",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({signalId,applicationId})}),d=await r.json();if(!r.ok)throw new Error(d.error||"Could not match email");await load()}catch(e){setError(e instanceof Error?e.message:"Could not match email")}finally{setBusy(null)}}
 async function apply(s:Signal){const id=s.applicationId||s.application?.id;if(!id||!s.suggestedStatus)return;setBusy(s.id);try{const r=await fetch("/api/gmail/signals/apply",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({signalId:s.id,applicationId:id})}),d=await r.json();if(!r.ok)throw new Error(d.error||"Could not update tracker");await load()}catch(e){setError(e instanceof Error?e.message:"Could not update tracker")}finally{setBusy(null)}}
 async function followUp(s:Signal){const id=s.applicationId||s.application?.id;if(!id)return;setDraftBusy(s.id);setError("");try{const r=await fetch("/api/intelligence/follow-up",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({applicationId:id,signalId:s.id})}),d=await r.json();if(!r.ok)throw new Error(d.error||"Could not generate draft");setDraft(d.draft)}catch(e){setError(e instanceof Error?e.message:"Could not generate draft")}finally{setDraftBusy(null)}}
 async function disconnect(){if(!confirm("Disconnect Gmail from JobPilot?"))return;await fetch("/api/gmail/status",{method:"DELETE"});setStatus({connected:false});setSignals([]);setTimeline([])}
 async function analyze(){setLoading(true);setPreview(null);try{const r=await fetch("/api/intelligence/email-preview",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({subject,body})}),d=await r.json();if(!r.ok)throw new Error(d.error||"Could not analyze email.");setPreview(d.signal)}catch(e){setError(e instanceof Error?e.message:"Could not analyze email")}finally{setLoading(false)}}
 return <main className="analyze-page"><nav className="nav shell"><Link className="brand" href="/"><span className="brand-mark">✦</span>JobPilot<span className="brand-ai">AI</span></Link><span className="analyze-nav-label">APPLICATION INTELLIGENCE</span><Link className="nav-cta" href="/tracker">Tracker ↗</Link></nav><section className="analyze-shell shell"><div className="profile-header"><div><div className="eyebrow"><span className="pulse"/> Application intelligence</div><h1>Turn recruiter emails into <em>signals.</em></h1><p>Connect Gmail to find application updates, extract recruiter details, and match messages to saved applications. Every tracker update still requires your approval.</p></div></div>
 <div className="profile-card profile-wide"><small className="kicker">GMAIL CONNECTION</small>{status?.connected?<><div className="recommendation"><strong>Gmail connected</strong><p>{status.connection?.email||"Connected account"}</p><span>Read-only access · Connected {status.connection?.connectedAt?new Date(status.connection.connectedAt).toLocaleDateString():""}</span></div><div className="profile-actions"><button className="button primary" onClick={scan} disabled={scanning}>{scanning?"Scanning inbox…":"Scan inbox ↗"}</button><button className="button secondary" onClick={disconnect}>Disconnect</button></div></>:<><p>Connect the Gmail account you use for job applications. You will be redirected to Google to approve access.</p><div className="profile-actions"><a className="button primary" href="/api/gmail/connect">Connect Gmail with Google ↗</a></div></>}</div>
 {error&&<div className="source-notice error">{error}</div>}
 <div className="profile-card profile-wide"><div className="section-heading"><div><small className="kicker">INBOX SIGNALS</small><h2>{signals.length?`${signals.length} detected updates`:`No detected updates yet`}</h2></div></div>{signals.length===0?<p>Connect Gmail and run a scan. Detected interview, assessment, offer, rejection, and application-confirmation emails will appear here.</p>:<div className="signal-list">{signals.map(s=>{const linked=s.application?.job||s.job;const needs=!s.application&&!s.applied;return <div className="signal-row" key={s.id}><div className="signal-main"><div className="signal-heading"><span className="signal-category">{s.category.replaceAll("_"," ")}</span><span className="status-pill">{method(s.matchMethod)} · {confidence(s.matchedScore??s.confidence)}</span></div><h3>{linked?.title||s.subject||"Application email"}</h3><p>{linked?.company||s.sender||"Unknown sender"}{linked?.location?` · ${linked.location}`:""}</p>{(s.recruiterName||s.recruiterEmail)&&<div className="recruiter-line"><b>Recruiter:</b> {s.recruiterName||"Unknown"}{s.recruiterEmail?` · ${s.recruiterEmail}`:""}</div>}<small>{s.reason}{s.receivedAt?` · ${new Date(s.receivedAt).toLocaleString()}`:""}</small>{needs&&<div className="match-review"><strong>{s.ambiguous?"AI found more than one plausible application":"Choose the correct application"}</strong><select defaultValue="" disabled={busy===s.id} onChange={e=>e.target.value&&match(s.id,e.target.value)}><option value="">Select a saved application…</option>{applications.map(a=>a.job&&<option key={a.id} value={a.id}>{a.job.title} — {a.job.company}</option>)}</select><small>Matching only links the email; it does not update the tracker.</small></div>}</div><div className="signal-action">{s.applied?<span className="status-pill">✓ Tracker updated</span>:s.applicationId||s.application?<><button className="button secondary" onClick={()=>followUp(s)} disabled={draftBusy===s.id}>{draftBusy===s.id?"Drafting…":"Follow up"}</button><button className="button primary" onClick={()=>apply(s)} disabled={busy===s.id}>{busy===s.id?"Updating…":`Approve → ${s.suggestedStatus||"Update"}`}</button></>:<span className="status-pill">Needs application match</span>}</div></div>})}</div>}</div>
 <div className="profile-card profile-wide"><div className="section-heading"><div><small className="kicker">APPLICATION TIMELINE</small><h2>Your recruiting journey</h2></div></div>{timeline.length===0?<p>Once an email is matched to an application, its interview, assessment, offer, rejection, and application updates will appear here.</p>:<div className="timeline-list">{timeline.map(t=><div className="timeline-card" key={t.applicationId}><div className="timeline-head"><div><h3>{t.job.title}</h3><p>{t.job.company}{t.job.location?` · ${t.job.location}`:""}</p></div><span className="status-pill">{t.status}</span></div><div className="timeline-events"><div className="timeline-event"><span className="timeline-dot"/><div><b>Application created</b><small>{new Date(t.createdAt).toLocaleString()}</small></div></div>{t.events.map(e=><div className="timeline-event" key={e.id}><span className="timeline-dot"/><div><b>{eventLabel(e.category)}{e.status?` → ${e.status}`:""}</b><small>{e.subject||e.reason}{e.receivedAt?` · ${new Date(e.receivedAt).toLocaleString()}`:""}</small>{e.recruiterName&&<small>Recruiter: {e.recruiterName}{e.recruiterEmail?` · ${e.recruiterEmail}`:""}</small>}</div></div>)}</div></div>)}</div>}</div>
 <div className="profile-card profile-wide"><small className="kicker">EMAIL PREVIEW</small><p>Test the classifier without connecting Gmail.</p><label>Subject<input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Interview invitation — Project Coordinator"/></label><label>Email body<textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Paste a recruiter or ATS message…" rows={7}/></label><button className="button secondary" onClick={analyze} disabled={loading||(!subject&&!body)}>{loading?"Analyzing…":"Analyze email"}</button>{preview&&<div className="recommendation"><strong>{preview.category.replaceAll("_"," ").toUpperCase()}</strong><p>{preview.reason}</p>{preview.suggestedStatus&&<span>Suggested status: <b>{preview.suggestedStatus}</b> · {confidence(preview.confidence)}</span>}</div>}</div>
 {draft&&<div className="profile-card profile-wide"><div className="section-heading"><div><small className="kicker">RECRUITER FOLLOW-UP DRAFT</small><h2>Review before sending</h2></div><button className="button secondary" onClick={()=>setDraft(null)}>Close</button></div><label>Subject<input value={draft.subject} onChange={e=>setDraft({...draft,subject:e.target.value})}/></label><label>Message<textarea value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})} rows={10}/></label><div className="profile-actions"><button className="button primary" onClick={()=>navigator.clipboard?.writeText(`Subject: ${draft.subject}\n\n${draft.body}`)}>Copy draft</button><span className="source-notice">JobPilot never sends this automatically.</span></div></div>}
 </section></main>
}