"use client";
import { useEffect, useState } from "react";
import Link from "next/link";

type Signal={id:string;category:string;confidence:number;suggestedStatus:string|null;reason:string;subject?:string;sender?:string;receivedAt?:string;applied:boolean;applicationId?:string|null;job?:{title:string;company:string}|null;application?:{id:string;job:{title:string;company:string}}|null};
type GmailStatus={connected:boolean;connection?:{email?:string;connectedAt?:string}|null};
export default function IntelligencePage(){const[status,setStatus]=useState<GmailStatus|null>(null);const[signals,setSignals]=useState<Signal[]>([]);const[scanning,setScanning]=useState(false);const[applying,setApplying]=useState<string|null>(null);const[error,setError]=useState("");const[subject,setSubject]=useState("");const[body,setBody]=useState("");const[preview,setPreview]=useState<any>(null);const[loading,setLoading]=useState(false);
async function load(){try{const[s,a]=await Promise.all([fetch("/api/gmail/status"),fetch("/api/gmail/signals")]);if(s.status===401){location.href="/login";return}const sd=await s.json(),ad=await a.json();setStatus(sd);setSignals(ad.signals||[])}catch{setError("Could not load Gmail intelligence.")}}
useEffect(()=>{load();const q=new URLSearchParams(location.search);if(q.get("gmail")==="error")setError("Google connection failed. Check your OAuth configuration and try again.");if(q.get("gmail")==="reauthorize")setError("Google did not return a refresh token. Reconnect and approve Gmail access.")},[]);
async function scan(){setScanning(true);setError("");try{const r=await fetch("/api/gmail/scan",{method:"POST"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Scan failed.");await load()}catch(e){setError(e instanceof Error?e.message:"Gmail scan failed.")}finally{setScanning(false)}}
async function apply(signal:Signal){if(!signal.suggestedStatus)return;const applicationId=signal.applicationId||signal.application?.id;if(!applicationId){setError("This signal is not linked to a saved application yet. Open the tracker and save the matching job first.");return}setApplying(signal.id);try{const r=await fetch("/api/gmail/signals/apply",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({signalId:signal.id,applicationId})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not update tracker.");await load()}catch(e){setError(e instanceof Error?e.message:"Could not apply signal.")}finally{setApplying(null)}}
async function disconnect(){if(!confirm("Disconnect Gmail from JobPilot?"))return;await fetch("/api/gmail/status",{method:"DELETE"});setStatus({connected:false});setSignals([])}
async function analyze(){setLoading(true);setPreview(null);try{const r=await fetch("/api/intelligence/email-preview",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({subject,body})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not analyze email.");setPreview(d.signal)}catch(e){setError(e instanceof Error?e.message:"Could not analyze email.")}finally{setLoading(false)}}
return <main className="analyze-page"><nav className="nav shell"><Link className="brand" href="/"><span className="brand-mark">✦</span>JobPilot<span className="brand-ai">AI</span></Link><span className="analyze-nav-label">APPLICATION INTELLIGENCE</span><Link className="nav-cta" href="/tracker">Tracker ↗</Link></nav><section className="analyze-shell shell"><div className="profile-header"><div><div className="eyebrow"><span className="pulse"/> Application intelligence</div><h1>Turn recruiter emails into <em>signals.</em></h1><p>Connect Gmail to find application updates, then approve proposed tracker changes. JobPilot uses read-only Gmail access and never submits applications from your mailbox.</p></div></div>
<div className="profile-card profile-wide"><small className="kicker">GMAIL CONNECTION</small>{status?.connected?<><div className="recommendation"><strong>Gmail connected</strong><p>{status.connection?.email||"Connected account"}</p><span>Read-only access · Connected {status.connection?.connectedAt?new Date(status.connection.connectedAt).toLocaleDateString():""}</span></div><div className="profile-actions"><button className="button primary" onClick={scan} disabled={scanning}>{scanning?"Scanning inbox…":"Scan inbox ↗"}</button><button className="button secondary" onClick={disconnect}>Disconnect</button></div></>:<><p>Connect the Gmail account you use for job applications. You will be redirected to Google to approve access.</p><div className="profile-actions"><a className="button primary" href="/api/gmail/connect">Connect Gmail with Google ↗</a></div></>}</div>
{error&&<div className="source-notice error">{error}</div>}
<div className="profile-card profile-wide"><div className="section-heading"><div><small className="kicker">INBOX SIGNALS</small><h2>{signals.length?`${signals.length} detected updates`:`No detected updates yet`}</h2></div></div>{signals.length===0?<p>Connect Gmail and run a scan. Detected interview, assessment, offer, rejection, and application-confirmation emails will appear here.</p>:<div className="signal-list">{signals.map(s=><div className="signal-row" key={s.id}><div><strong>{s.category.replaceAll("_"," ")}</strong><h3>{s.job?.title||s.application?.job?.title||s.subject||"Application email"}</h3><p>{s.job?.company||s.application?.job?.company||s.sender||"Unknown sender"}</p><small>{s.reason} · {Math.round(s.confidence*100)}% confidence</small></div><div className="signal-action">{s.applied?<span className="status-pill">Applied to tracker</span>:s.suggestedStatus&&(s.applicationId||s.application)?<button className="button primary" onClick={()=>apply(s)} disabled={applying===s.id}>{applying===s.id?"Updating…":`Approve → ${s.suggestedStatus}`}</button>:<span className="status-pill">Save matching job first</span>}</div></div>)}</div>}</div>
<div className="profile-card profile-wide"><small className="kicker">EMAIL PREVIEW</small><p>Test the classifier without connecting Gmail.</p><label>Subject<input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Interview invitation — Project Coordinator"/></label><label>Email body<textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Paste a recruiter or ATS message…" rows={7}/></label><button className="button secondary" onClick={analyze} disabled={loading||(!subject&&!body)}>{loading?"Analyzing…":"Analyze email"}</button>{preview&&<div className="recommendation"><strong>{preview.category.replaceAll("_"," ").toUpperCase()}</strong><p>{preview.reason}</p>{preview.suggestedStatus&&<span>Suggested status: <b>{preview.suggestedStatus}</b> · {Math.round(preview.confidence*100)}%</span>}</div>}</div>
</section></main>}
