"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";

type Job={id:string;title:string;company:string;location:string};
type Application={id:string;status:string;job:Job};
type Signal={id:string;subject:string;from:string;snippet?:string;receivedAt?:string;createdAt:string;suggestedStatus?:string;matchedScore?:number;matchMethod?:string;ambiguous:boolean;applied:boolean;application?:Application|null;job?:Job|null};

const STATUS_RANK:Record<string,number>={Saved:0,Preparing:1,Applied:2,Interview:3,Offer:4,Rejected:4};
function canMove(from:string,to:string){return from===to||(from in STATUS_RANK&&to in STATUS_RANK&&STATUS_RANK[to]>=STATUS_RANK[from]);}

export default function SignalsPage(){
 const[signals,setSignals]=useState<Signal[]>([]),[apps,setApps]=useState<Application[]>([]),[loaded,setLoaded]=useState(false),[error,setError]=useState(""),[matching,setMatching]=useState("");
 useEffect(()=>{(async()=>{try{const[s,a]=await Promise.all([fetch("/api/gmail/signals"),fetch("/api/applications")]);if(s.status===401||a.status===401){location.href="/login";return}const sd=await s.json(),ad=await a.json();if(!s.ok)throw new Error(sd.error||"Could not load Gmail signals");if(!a.ok)throw new Error(ad.error||"Could not load applications");setSignals(sd.signals||[]);setApps((ad.applications||[]).map((x:any)=>({...x.job,id:x.id,status:x.status,job:x.job})));}catch(e:any){setError(e.message||"Could not load signals")}finally{setLoaded(true)}})()},[]);
 const pending=useMemo(()=>signals.filter(s=>!s.applied&&s.ambiguous),[signals]);
 async function match(signalId:string,applicationId:string){setMatching(signalId);setError("");try{const r=await fetch("/api/gmail/signals",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({signalId,applicationId})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not match email");setSignals(x=>x.map(s=>s.id===signalId?{...s,...d.signal,application:d.application,ambiguous:false,matchMethod:"manual",matchedScore:1}:s));}catch(e:any){setError(e.message||"Could not match email")}finally{setMatching("")}}
 return <main className="analyze-page"><nav className="nav shell"><Link className="brand" href="/"><span className="brand-mark">✦</span>JobPilot<span className="brand-ai">AI</span></Link><span className="analyze-nav-label">GMAIL SIGNALS</span><Link className="nav-cta" href="/tracker">Tracker ↗</Link></nav><section className="tracker-shell shell"><div className="jobs-header"><div><div className="eyebrow"><span className="pulse"/> Email intelligence</div><h1>Turn inbox signals into <em>application updates.</em></h1><p>Review ambiguous hiring emails and connect them to the right application. High-confidence signals can already be applied automatically.</p></div><div className="match-summary"><strong>{pending.length}</strong><span>needs review</span></div></div>{error&&<div className="source-notice error">{error}</div>}{!loaded?<div className="empty-profile"><h2>Loading signals…</h2></div>:!signals.length?<div className="empty-profile"><h2>No Gmail signals yet.</h2><p>Connect Gmail and scan your inbox to detect application updates.</p><Link className="button primary" href="/settings">Connect Gmail ↗</Link></div>:<div className="tracker-list">{signals.map(s=><article className="tracker-card" key={s.id}><div className="tracker-card-top"><div><small>{s.from||"Gmail"}{s.receivedAt?` · ${new Date(s.receivedAt).toLocaleDateString()}`:""}</small><h2>{s.subject||"Application email"}</h2><span>{s.job?.company||s.application?.job?.company||"Unmatched"}{s.job?.title?` · ${s.job.title}`:""}</span></div><span className="status-pill">{s.applied?"Applied automatically":s.ambiguous?"Needs review":(s.suggestedStatus||"Signal")}</span></div><div className="tracker-tailored"><strong>{s.suggestedStatus||"Application update"}</strong><span>{s.snippet||"JobPilot detected a hiring-related email."}</span>{s.matchMethod&&<span>Match: {s.matchMethod} · {Math.round((s.matchedScore||0)*100)}%</span>}</div>{s.ambiguous&&!s.applied&&<div className="tracker-card-bottom"><select defaultValue="" disabled={matching===s.id} onChange={e=>e.target.value&&match(s.id,e.target.value)}><option value="">Match to an application…</option>{apps.filter(a=>canMove(a.status,s.suggestedStatus||a.status)).map(a=><option key={a.id} value={a.id}>{a.job?.company} — {a.job?.title} ({a.status})</option>)}</select><Link className="button secondary" href="/tracker">Open tracker ↗</Link></div>}{s.application&&!s.ambiguous&&<div className="tracker-card-bottom"><Link className="button secondary" href={`/application/${encodeURIComponent(s.application.id)}`}>View application ↗</Link></div>}</article>)}</div>}</section><footer className="analyze-footer shell"><span>✦ JobPilot AI</span><span>Gmail intelligence</span><span>Review with confidence.</span></footer></main>
}
