"use client";

import { useEffect, useState } from "react";
import Link from "next/link";

type Package = { fitSummary:string; tailoredSummary:string; resumeEdits:{section:string;original:string;suggested:string;reason:string}[]; coverLetter:string; missingRequirements:string[]; applicationRecommendation:string };
type Job = { title:string; company:string; location:string; description:string; skills:string[]; mode:string; level:string; url?:string };

export default function TailorPage(){
 const [profile,setProfile]=useState<any>(null); const [job,setJob]=useState<Job|null>(null); const [result,setResult]=useState<Package|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 useEffect(()=>{try{const p=localStorage.getItem("jobpilot-career-profile");const j=localStorage.getItem("jobpilot-selected-job");if(p)setProfile(JSON.parse(p));if(j)setJob(JSON.parse(j));}catch{}},[]);
 async function generate(){if(!profile||!job)return;setLoading(true);setError("");try{const r=await fetch("/api/tailor",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({profile,job})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not tailor application.");setResult(d.result);}catch(e){setError(e instanceof Error?e.message:"Could not tailor application.");}finally{setLoading(false)}}
 return <main className="analyze-page tailor-page"><nav className="nav shell"><Link className="brand" href="/"><span className="brand-mark">✦</span>JobPilot<span className="brand-ai">AI</span></Link><span className="analyze-nav-label">TAILORED APPLICATION</span><Link className="nav-cta" href="/jobs">Back to jobs ↗</Link></nav>
 <section className="tailor-shell shell"><div className="profile-header"><div><div className="eyebrow"><span className="pulse"/> Truth-first application</div><h1>Make the application <em>fit.</em></h1><p>JobPilot rewrites and reframes only what your profile can genuinely support. No invented achievements or keywords.</p></div></div>
 {!job?<div className="empty-profile"><h2>Select a job first.</h2><p>Return to the job matching page and choose an opportunity to tailor.</p><Link className="button primary" href="/jobs">Find a job ↗</Link></div>:<><div className="selected-job"><small>SELECTED OPPORTUNITY</small><h2>{job.title}</h2><p>{job.company} · {job.location} · {job.mode}</p><div className="job-tags">{job.skills?.map(x=><span key={x}>{x}</span>)}</div></div>{!result?<div className="generate-card"><h2>Ready to tailor this application?</h2><p>You'll get a targeted professional summary, suggested resume edits, a cover letter and a clear list of missing requirements.</p>{error&&<div className="source-notice error">{error}</div>}<button className="button primary" onClick={generate} disabled={loading||!profile}>{loading?"Building application package…":"Tailor my application ↗"}</button></div>:<div className="tailor-results"><div className="recommendation"><small>RECOMMENDATION</small><strong>{result.applicationRecommendation.toUpperCase()}</strong><p>{result.fitSummary}</p></div><article className="profile-card profile-wide"><small className="kicker">TAILORED PROFESSIONAL SUMMARY</small><p>{result.tailoredSummary}</p></article><article className="profile-card profile-wide"><small className="kicker">RESUME EDITS</small>{result.resumeEdits.map((x,i)=><div className="edit-row" key={i}><b>{x.section}</b><div><small>CHANGE TO</small><p>{x.suggested}</p><small>WHY</small><span>{x.reason}</span></div></div>)}</article><article className="profile-card profile-wide"><small className="kicker">COVER LETTER</small><textarea readOnly value={result.coverLetter}/></article><article className="profile-card profile-wide"><small className="kicker">MISSING REQUIREMENTS</small>{result.missingRequirements.length?<ul>{result.missingRequirements.map(x=><li key={x}>{x}</li>)}</ul>:<p>No obvious missing requirements from the supplied job/profile data.</p>}</article><div className="profile-actions"><button className="button primary" onClick={()=>navigator.clipboard?.writeText(result.coverLetter)}>Copy cover letter</button>{job.url&&<a className="button secondary" href={job.url} target="_blank" rel="noreferrer">Open original listing ↗</a>}<button className="button secondary" onClick={()=>setResult(null)}>Regenerate</button></div><p className="truth-note">Review every suggested change before submitting. JobPilot assists with preparation; it does not guarantee an interview or hiring outcome.</p></div>}</>}
 </section><footer className="analyze-footer shell"><span>✦ JobPilot AI</span><span>Tailored application</span><span>Truth over keyword stuffing.</span></footer></main>;
}
