"use client";
import Link from "next/link";
import { useEffect,useState } from "react";

type App={id:string;status:string;job:{title:string;company:string;location:string;url:string|null};tailoredApplication?:unknown};
export default function AutomationPage(){
 const [apps,setApps]=useState<App[]>([]),[selected,setSelected]=useState<string[]>([]),[plan,setPlan]=useState<any>(null),[loading,setLoading]=useState(true);
 useEffect(()=>{fetch("/api/applications").then(r=>r.json()).then(x=>setApps(x.applications||[])).finally(()=>setLoading(false));},[]);
 const toggle=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 const prepare=async()=>{setPlan(null);const r=await fetch("/api/automation/prepare",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({applicationIds:selected})});setPlan(await r.json());};
 return <main><nav className="nav shell"><Link className="brand" href="/dashboard"><span className="brand-mark">✦</span>JobPilot<span className="brand-ai">AI</span></Link><div className="nav-actions"><Link href="/tracker">Tracker</Link><Link className="nav-cta" href="/dashboard">Command center ↗</Link></div></nav><section className="automation-shell shell"><div className="eyebrow"><span className="pulse"/> Controlled execution</div><h1>Apply with <em>confidence.</em></h1><p className="automation-lede">JobPilot can prepare the work, open the right path, and keep every high-impact submission under your control.</p><div className="automation-trust"><b>USER CONTROLLED</b><span>No application is submitted automatically.</span></div><div className="automation-grid"><section className="automation-card"><div className="preference-heading"><div><div className="kicker">SELECT APPLICATIONS</div><h2>Build an application run</h2></div><span className="preference-badge">{selected.length} selected</span></div>{loading?<p className="truth-note">Loading your applications…</p>:apps.length?<div className="automation-list">{apps.filter(a=>a.status!=="Rejected").map(a=><label className={`automation-row ${selected.includes(a.id)?"selected":""}`} key={a.id}><input type="checkbox" checked={selected.includes(a.id)} onChange={()=>toggle(a.id)}/><div><strong>{a.job.title}</strong><span>{a.job.company} · {a.job.location}</span></div><small>{a.tailoredApplication?"TAILORED":"NEEDS TAILORING"}</small></label>)}</div>:<p className="truth-note">Save a job in the Tracker first.</p>}<button className="button primary" disabled={!selected.length} onClick={prepare}>Prepare workflow →</button></section><section className="automation-card"><div className="kicker">HOW IT WORKS</div><h2>Three deliberate steps</h2><div className="workflow"><div><b>01</b><span>Review</span><p>Check the tailored CV and cover letter.</p></div><div><b>02</b><span>Open</span><p>Use the employer's permitted application route.</p></div><div><b>03</b><span>Confirm</span><p>You make the final submission decision.</p></div></div></section></div>{plan?.steps&&<section className="automation-result"><div className="kicker">READY TO EXECUTE</div><h2>{plan.count} workflow{plan.count===1?"":"s"} prepared</h2>{plan.steps.map((x:any)=><div className="automation-plan" key={x.applicationId}><div><strong>{x.job.title}</strong><span>{x.job.company}</span></div><div className="plan-steps">{x.steps.map((s:any)=><span key={s.key}>{s.completed?"✓":"○"} {s.label}</span>)}</div>{x.job.url&&<a className="button secondary" href={x.job.url} target="_blank" rel="noreferrer">Open application ↗</a>}</div>)}<p className="truth-note">The final submission remains manual. JobPilot never silently submits an application.</p></section>}</section></main>}
