"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Job = { id:string; title:string; company:string; location:string; mode?:string; level?:string; salary?:string; url?:string; description?:string; skills?:string[]; matchScore:number; recommendation?:"Apply"|"Consider"|"Skip"; matchedSkills?:string[]; missingSkills?:string[]; matchedSignals?:string[] };

export default function DiscoverPage(){
 const [jobs,setJobs]=useState<Job[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [saved,setSaved]=useState<Record<string,boolean>>({});
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/jobs/recommend",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not load recommendations.");const base=d.recommendations||[];if(!base.length){setJobs([]);return}const m=await fetch("/api/jobs/match",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({jobs:base}),cache:"no-store"});const md=await m.json();if(!m.ok)throw new Error(md.error||"Could not calculate profile matches.");const byKey=new Map((md.jobs||[]).map((x:any)=>[`${x.job.title}|${x.job.company}|${x.job.location}`,x.match]));setJobs(base.map((job:Job)=>{const match=byKey.get(`${job.title}|${job.company}|${job.location}`);return match?{...job,matchScore:match.score,recommendation:match.recommendation,matchedSkills:match.matchedSkills,missingSkills:match.missingSkills,matchedSignals:match.matchedSignals}:job}))}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function save(job:Job){const r=await fetch("/api/applications",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({job,status:"Saved"})});if(r.ok)setSaved(x=>({...x,[job.id]:true}));}
 return <main className="page-shell"><nav className="nav shell"><Link className="brand" href="/"><span className="brand-mark">✦</span>JobPilot<span className="brand-ai">AI</span></Link><div className="nav-actions"><Link href="/agent">Agent</Link><Link className="nav-cta" href="/tracker">Tracker ↗</Link></div></nav><section className="jobs-shell shell"><div className="jobs-header"><div><div className="eyebrow"><span className="pulse"/> Job discovery agent</div><h1>New opportunities,<br/><em>ranked for you.</em></h1><p>JobPilot removes already-tracked roles and ranks available listings against the evidence in your career profile and job preferences.</p></div><button className="button secondary" onClick={load}>Refresh</button></div>{error&&<div className="source-notice error">{error}</div>}{loading?<div className="empty-profile"><h2>Ranking opportunities…</h2><p>Comparing live workspace jobs with your profile.</p></div>:<div className="job-list">{jobs.map(job=><article className="job-card" key={job.id}><div className="job-card-main"><div className="company-icon">{job.company[0]?.toUpperCase()}</div><div><div className="job-meta">{job.company} · {job.location}</div><h2>{job.title}</h2><p>{(job.description||"").replace(/<[^>]+>/g," ").slice(0,260)}{(job.description||"").length>260?"…":""}</p><div className="job-tags">{(job.matchedSkills||job.skills||[]).slice(0,4).map(s=><span key={s}>✓ {s}</span>)}{job.missingSkills?.slice(0,2).map(s=><span key={`missing-${s}`}>Missing: {s}</span>)}{job.mode&&<span>{job.mode}</span>}{job.level&&<span>{job.level}</span>}</div><div style={{marginTop:12,fontSize:13,opacity:.78}}>{job.matchedSignals?.join(" · ")||"Profile-based match"}{job.missingSkills?.length?` · ${job.missingSkills.length} skill${job.missingSkills.length===1?"":"s"} to strengthen`:""}</div></div></div><div className="job-match"><strong>{job.matchScore}%</strong><small>PROFILE FIT</small><div style={{fontSize:12,fontWeight:700,margin:"4px 0 10px"}}>{job.recommendation||"Consider"}</div><button className="button secondary" disabled={saved[job.id]} onClick={()=>save(job)}>{saved[job.id]?"Saved ✓":"Save job"}</button><Link className="button primary" href={`/tailor?job=${encodeURIComponent(job.id)}`}>Tailor ↗</Link>{job.url&&<a className="button secondary" href={job.url} target="_blank" rel="noreferrer">View ↗</a>}</div></article>)}{!jobs.length&&!error&&<div className="empty-profile"><h2>No new strong matches.</h2><p>Refresh after new listings arrive or broaden your job preferences.</p><Link className="button primary" href="/profile">Adjust preferences ↗</Link></div>}</div>}</section></main>}
