import { NextResponse } from "next/server";
import { getCurrentUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { safeHttpUrl, stringArrayField, stringField, optionalStringField } from "@/lib/validate";
import { rateLimit, rateLimitResponse } from "@/lib/rate-limit";
const ALLOWED=["Saved","Preparing","Applied","Interview","Offer","Rejected"] as const;
const RANK:Record<string,number>={Saved:0,Preparing:1,Applied:2,Interview:3,Offer:4,Rejected:4};
function guard(userId:string,action:string){return rateLimitResponse(rateLimit(`applications:${action}:${userId}`,action==="read"?60:30,60_000));}
function bodyTooLarge(req:Request){const n=req.headers.get("content-length");return n!==null&&Number.isFinite(Number(n))&&Number(n)>128*1024;}
function validStatus(v:unknown):v is typeof ALLOWED[number]{return typeof v==="string"&&(ALLOWED as readonly string[]).includes(v);}
function canTransition(from:string,to:string){return from===to||(from in RANK&&to in RANK&&RANK[to]>=RANK[from]);}
function parseDate(v:unknown){if(v===null)return null;if(typeof v!=="string"||!v.length)return undefined;const d=new Date(v);return Number.isNaN(d.getTime())?"invalid":d;}
export async function GET(){const user=await getCurrentUser();if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});const limited=guard(user.id,"read");if(limited)return limited;const applications=await prisma.application.findMany({where:{userId:user.id},include:{job:true,tailoredApplication:true},orderBy:{updatedAt:"desc"},take:100});return NextResponse.json({applications,limit:100});}
export async function POST(req:Request){const user=await getCurrentUser();if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});const limited=guard(user.id,"write");if(limited)return limited;if(bodyTooLarge(req))return NextResponse.json({error:"Request body is too large."},{status:413});try{const b=await req.json();if(!b||typeof b!=="object"||!b.job||typeof b.job!=="object")return NextResponse.json({error:"Job details are required."},{status:400});const j=b.job as Record<string,unknown>;const id=stringField(j.id,300,"Job id"),title=stringField(j.title,500,"Job title"),company=stringField(j.company,300,"Company"),location=optionalStringField(j.location,500,"Location")??"",mode=optionalStringField(j.mode,100,"Mode")??null,level=optionalStringField(j.level,100,"Level")??null,source=optionalStringField(j.source,100,"Source")??null,salary=optionalStringField(j.salary,500,"Salary")??null,description=optionalStringField(j.description,20000,"Description")??null,url=j.url?safeHttpUrl(j.url,"Job URL"):null,skills=j.skills===undefined?[]:stringArrayField(j.skills,100,200,"Skills");if(b.status!==undefined&&!validStatus(b.status))return NextResponse.json({error:"Invalid status."},{status:400});const notes=b.notes===undefined?"":stringField(b.notes,10000,"Notes");const job=await prisma.job.upsert({where:{id},create:{id,title,company,location,mode,level,source,salary,url,description,skills},update:{title,company,location,mode,level,source,salary,url,description,skills}});const existing=await prisma.application.findUnique({where:{userId_jobId:{userId:user.id,jobId:job.id}}});const requested=b.status===undefined?"Saved":String(b.status);if(existing&&!canTransition(existing.status,requested))return NextResponse.json({error:`Cannot move application backward from ${existing.status} to ${requested}.`},{status:409});const application=await prisma.application.upsert({where:{userId_jobId:{userId:user.id,jobId:job.id}},create:{userId:user.id,jobId:job.id,status:requested,notes},update:{status:requested,notes:b.notes===undefined?undefined:notes,appliedAt:requested==="Applied"&&!existing?.appliedAt?new Date():undefined},include:{job:true,tailoredApplication:true}});return NextResponse.json({application});}catch{return NextResponse.json({error:"Could not save application."},{status:400});}}
export async function PATCH(req:Request){const user=await getCurrentUser();if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});const limited=guard(user.id,"write");if(limited)return limited;if(bodyTooLarge(req))return NextResponse.json({error:"Request body is too large."},{status:413});try{const b=await req.json();if(!b||typeof b!=="object")return NextResponse.json({error:"Invalid request."},{status:400});const id=stringField(b.id,300,"Application id");if(b.status!==undefined&&!validStatus(b.status))return NextResponse.json({error:"Invalid status."},{status:400});const notes=b.notes===undefined?undefined:stringField(b.notes,10000,"Notes");const existing=await prisma.application.findFirst({where:{id,userId:user.id}});if(!existing)return NextResponse.json({error:"Application not found."},{status:404});const interviewCompletedAt=b.interviewCompletedAt===undefined?undefined:parseDate(b.interviewCompletedAt);if(interviewCompletedAt==="invalid")return NextResponse.json({error:"Invalid interview completion date."},{status:400});const followUpDueAt=b.followUpDueAt===undefined?undefined:parseDate(b.followUpDueAt);if(followUpDueAt==="invalid")return NextResponse.json({error:"Invalid follow-up date."},{status:400});const interviewOutcome=b.interviewOutcome===undefined?undefined:optionalStringField(b.interviewOutcome,100,"Interview outcome");if(interviewOutcome&&interviewCompletedAt===null)return NextResponse.json({error:"Interview outcome requires a completed interview."},{status:400});const requestedStatus=b.status===undefined?existing.status:String(b.status);const hasCompletedInterview=interviewCompletedAt instanceof Date?true:interviewCompletedAt===null?false:Boolean(existing.interviewCompletedAt);const effectiveStatus=hasCompletedInterview&&RANK[requestedStatus]<RANK.Interview?"Interview":requestedStatus;if(!canTransition(existing.status,effectiveStatus))return NextResponse.json({error:`Cannot move application backward from ${existing.status} to ${effectiveStatus}.`},{status:409});const application=await prisma.application.update({where:{id:existing.id},data:{status:effectiveStatus,notes,appliedAt:effectiveStatus==="Applied"&&!existing.appliedAt?new Date():undefined,interviewCompletedAt,interviewOutcome:interviewCompletedAt===null?null:interviewOutcome,followUpDueAt},include:{job:true,tailoredApplication:true}});return NextResponse.json({application});}catch{return NextResponse.json({error:"Could not update application."},{status:400});}}
export async function DELETE(req:Request){const user=await getCurrentUser();if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});const limited=guard(user.id,"write");if(limited)return limited;if(bodyTooLarge(req))return NextResponse.json({error:"Request body is too large."},{status:413});const b=await req.json().catch(()=>({}));if(!b||typeof b!=="object"||!b.id)return NextResponse.json({error:"Application id is required."},{status:400});try{const id=stringField(b.id,300,"Application id");const result=await prisma.application.deleteMany({where:{id,userId:user.id}});if(!result.count)return NextResponse.json({error:"Application not found."},{status:404});return NextResponse.json({ok:true});}catch{return NextResponse.json({error:"Could not delete application."},{status:400});}}
